- hosts: all
  gather_facts: yes
  vars:
    scan_use_checksum: false
    scan_use_recursive: false
  tasks:
  
    - name: Install bottle python package
      ansible.builtin.pip:
        name: ansible
        name: pyvmomi

    - name: Import common vars
      ansible.builtin.include_vars:
        file: vars.yml

    - name: "Get VM details"
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: vm_facts

    # - name: "Set VM IP Address as fact"
    #   set_fact:
    #     vm_ip: "{{ (vm_facts.virtual_machines | selectattr('guest_name', 'equalto', vm_name) | first).ip_address }}"

    # - name: "Display VM IP Address"
    #   debug:
    #     msg: "The IP address of the VM is {{ vm_ip }}"

