- hosts: all
  gather_facts: no
  vars:
    scan_use_checksum: false
    scan_use_recursive: false
  tasks:
    - name: Install pip
      community.general.easy_install:
        name: pip
        state: latest

    - name: Install bottle python package
      ansible.builtin.pip:
        name: ansible

    - name: "Get VM details"
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: vm_facts

    - name: "Set VM IP Address as fact"
      set_fact:
        vm_ip: "{{ (vm_facts.virtual_machines | selectattr('guest_name', 'equalto', vm_name) | first).ip_address }}"

    - name: "Display VM IP Address"
      debug:
        msg: "The IP address of the VM is {{ vm_ip }}"


- hosts: new_vms
  tasks:
    - name: "Ping the new VM"
      ansible.builtin.ping:
